devices:
  samplerate: 44100
  chunksize: 4096
  capture:
    type: CoreAudio
    device: "BlackHole 2ch"
    channels: 2
  playback:
    type: CoreAudio
    device: "D50 III"
    channels: 2

filters:
  preamp:
    type: Gain
    parameters:
      gain: -3.0
  filter1:
    type: Biquad
    parameters:
      type: Peaking
      freq: 95
      gain: -12.0
      q: 1.1
  filter2:
    type: Biquad
    parameters:
      type: Highshelf
      freq: 10000
      gain: 2.0
      q: 0.707
  filter3:
    type: Biquad
    parameters:
      type: Lowshelf
      freq: 60
      gain: 1.5
      q: 0.707
  filter4:
    type: Biquad
    parameters:
      type: Peaking
      freq: 180
      gain: 1.5
      q: 0.9
  filter5:
    type: Biquad
    parameters:
      type: Peaking
      freq: 500
      gain: -1.0
      q: 1.0
  filter6:
    type: Biquad
    parameters:
      type: Peaking
      freq: 3200
      gain: 1.5
      q: 1.0

pipeline:
  - type: Filter
    channels: [0, 1]
    names:
      - preamp
      - filter1
      - filter2
      - filter3
      - filter4
      - filter5
      - filter6
