devices:
  samplerate: 96000
  chunksize: 4096
  capture:
    type: CoreAudio
    device: BlackHole 2ch
    channels: 2
    format: FLOAT32LE
  playback:
    type: CoreAudio
    device: D50 III
    channels: 2
    format: S32LE
filters:
  volume:
    type: Gain
    parameters:
      gain: 0
pipeline:
  - type: Filter
    channels:
      - 0
      - 1
    names:
      - volume
