devices:
  samplerate: 96000
  chunksize: 4096
  capture:
    type: CoreAudio
    device: BlackHole 2ch
    channels: 2
    format: FLOAT32LE
  playback:
    type: CoreAudio
    device: D50 III
    channels: 2
    format: S32LE
filters:
  preamp:
    type: Gain
    parameters:
      gain: -3
  filter1:
    type: Biquad
    parameters:
      type: Peaking
      freq: 95
      gain: -5.5
      q: 1
  filter2:
    type: Biquad
    parameters:
      type: Highshelf
      freq: 10000
      gain: 2
      q: 0.707
  filter3:
    type: Biquad
    parameters:
      type: Lowshelf
      freq: 60
      gain: 2.5
      q: 0.707
  filter4:
    type: Biquad
    parameters:
      type: Peaking
      freq: 160
      gain: 1.5
      q: 0.9
  filter5:
    type: Biquad
    parameters:
      type: Peaking
      freq: 800
      gain: 1
      q: 1
  filter6:
    type: Biquad
    parameters:
      type: Peaking
      freq: 3200
      gain: 1.2
      q: 1
pipeline:
  - type: Filter
    channels:
      - 0
      - 1
    names:
      - preamp
      - filter1
      - filter2
      - filter3
      - filter4
      - filter5
      - filter6
